Repository geopython/GeoHealthCheck, pull requests merged in 2020-10, with the labels that each got.

#333 upgrade OWSLib to 0.20.0 and fix WFS3 (OAPIF) Probes
  GeoHealthCheck/config_main.py
  GeoHealthCheck/healthcheck.py
  GeoHealthCheck/plugins/probe/tms.py
  GeoHealthCheck/plugins/probe/wfs.py
  GeoHealthCheck/plugins/probe/wfs3.py
  GeoHealthCheck/util.py
  requirements.txt
  tests/data/fixtures.json
Labels: enhancement

#335 PR that fixes #334 make g.user.is_authenticated() an attribute
  GeoHealthCheck/app.py
Labels: bug

#337 added missing german translation
  GeoHealthCheck/translations/de/LC_MESSAGES/messages.po
Labels: translation

#338 #285 #313 Content Negotiation in OAFeat Probes and renaming for OAFeat
  GeoHealthCheck/enums.py
  GeoHealthCheck/healthcheck.py
  GeoHealthCheck/plugins/probe/wfs3.py
Labels: bug, enhancement

#341 update de translation. small fixes in wording
  GeoHealthCheck/translations/de/LC_MESSAGES/messages.po
Labels: translation
