Repository geopython/GeoHealthCheck, pull requests merged in 2021-07, with the labels that each got.

#382 PR for #364 upgrade Sphinx and RTD theme and adapt Sphinx config for RTD Theme
  GeoHealthCheck/plugins/resourceauth/resourceauths.py
  docs/conf.py
  docs/config.rst
  docs/install.rst
  requirements.txt
Labels: docs

#383 PR for #363 enable sphinx autodoc for RTD build
  GeoHealthCheck/init.py
  docker/scripts/requirements.txt
Labels: bug, docs

#376 Partial fix for #372: faster shutdown of ghc_web Docker container
  docker/scripts/run-web.sh
Labels: enhancement
